server:
  port: 8080

spring:
  application:
    name: hdt-gateway-server
  # [추가] 통합SI DB 접속 정보 (PollingAdapter용)
  datasource:
    driver-class-name: org.postgresql.Driver # MS-SQL 예시
    url: jdbc:postgresql://192.168.250.249:5432/hdt?currentSchema=core
    username: testuser
    password: 1q2w3e
    # [수정] 통합 SI 연계용 로컬 MS-SQL 설정
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.250.249:1433;databaseName=HDT_SI_DB;encrypt=false;trustServerCertificate=true
#    username: sa
#    password: HanaDream!2026

  kafka:
    bootstrap-servers: 192.168.250.249:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        max.request.size: 4194304

management:
  endpoints:
    web:
      exposure:
        include: info, metrics, health, mappings

# 통합SI 테이터 호출 URL
external:
  vendor:
    base-url: "http://localhost:9999"

# Event 서버 주소
internal:
  event:
    base-url: "http://localhost:8081"

hdt:
  kafka:
    topic:
      raw: hdt-telemetry-raw